version: '3.8'

services:
  web_search_api:
    build:
      context: .
      dockerfile: Backend/Dockerfile
      args:
        BASE_IMAGE: ${BACKEND_BASE_IMAGE:-python:3.11-slim}
    container_name: web_search_api
    expose:
      - "8383"
    command: ["python", "-m", "uvicorn", "Backend.Web_Search.src.WebSearchAPI:app", "--host", "0.0.0.0", "--port", "8383"]

  request_manager:
    build:
      context: .
      dockerfile: Backend/Dockerfile
      args:
        BASE_IMAGE: ${BACKEND_BASE_IMAGE:-python:3.11-slim}
    container_name: request_manager
    expose:
      - "8181"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: [ "python", "-m", "uvicorn", "Backend.Report_Compose.src.RequestsMngrAPI:app", "--host", "0.0.0.0", "--port", "8181" ]

  web_server:
    build:
      context: .
      dockerfile: Webserver/Dockerfile
    container_name: strvthr_websrv_nginx
    ports:
      - "5155:5155"
    depends_on:
      - request_manager